### ISSUE TITLE
support nova-volume or nova-netwtork

### ISSUE THREAD

**Issue by frank-zera** [gondor/openstack4j#206]
Hi, gondor,
i want to using os4j for my project, but i can not find the api for nova volue and nova network.
would os4j support them in the future?

**Comment by gondor** [comment]
I need more information.  Many of the nova services including network are intermixed within volumes() or network().  Let me know what "exactly" your trying to do, ie.  post a few of the CLI commands your trying to do and I can tell you if we support them and what they are in OS4j or not.

If it's something you could do in openstack-java-sdk then it should for sure be in os4j since we support more coverage of openstack than that API.

**Comment by frank-zera** [comment]
gondor,
thank you for your reply.
i find all these things yestaday.
os4j updates faster than openstack-java-sdk, thank you for your work hard.

**Comment by gondor** [comment]
No problem! Welcome to our community :)
