### ISSUE TITLE
I need some help getting the basics working

### ISSUE THREAD

**Issue by downzero** [gondor/openstack4j#207]
I am using eclipse with java 7.  I imported the openstack4j-2.0.2-20150116.170119-2-withdeps-sources.jar file into a project.  I'm following the getting started guide here: http://www.openstack4j.com/learn/getting-started/

I can't get the authentication to compile:
OSClient os = OSFactory.builder()
                       .endpoint("http://127.0.0.1:5000/v2.0")
                       .credentials("admin","sample")
                       .tenantName("admin")
                       .authenticate();

It tells me it can't get OSClient to resolve to a type, and can't resolve OSFactory.  I have the imports set to:
import org.openstack4j.openstack.*;
import org.openstack4j.api.*;

I will fill in my endpoint and creds later when I can get this to work.  Any ideas?

**Comment by gondor** [comment]
Any reason why your not using Maven in your project to play around?  Otherwise the JAR you mentioned above would not work.  It's a "sources" jar which means it contains raw source and nothing is compile.  Try the non-sources jar:  https://oss.sonatype.org/content/repositories/snapshots/org/pacesys/openstack4j/2.0.2-SNAPSHOT/openstack4j-2.0.2-20150116.170119-2-withdeps.jar

**Comment by downzero** [comment]
Hey Jeremy...dumb mistake on my part.  I've got it compiling now.  Thanks.

**Comment by gondor** [comment]
No problem! Glad you got it running.
