### ISSUE TITLE
Add support for Sahara data processing

### ISSUE THREAD

**Issue by ekasitk** [gondor/openstack4j#215]
I would like to add support for sahara (http://docs.openstack.org/developer/sahara/) into openstack4j. I've already done some coding and testing. It's still in infancy but the result so far is good. 

Any suggestions?

**Comment by gondor** [comment]
That sounds good.  What I suggest is adding the SaharaService off of the OSClient.   Since sahara is not associated with Compute, Networking, etc.   For example this would give you:

```java
os.saraha().someOtherCallOrService
```

Otherwise thank you and please make sure you follow the same patterns seen throughout the existing OpenStack4j project (comments, indentation (spaces not tabs (4 spaces)), naming patterns).  When you finish and do a pull request I will do a code review and then provide and suggestions if any before accepting the merge.

**Comment by octupszhang** [comment]
I'm looking forward to it, we plan to use sahara recently.

**Comment by gondor** [comment]
Deploying 2.0.2 Release Tonight - Closing - Re-Open new issue for additional support for Sahara
