### ISSUE TITLE
Unable to capture Create Subnet Error..

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#249]
Below is the request I am sending to create a subnet.. Here you can see, a false cidr is sent.. 

I am able to catch an exception, but not the "NeutronError" Message.. Is there any way I could capture the NeutronError sent by OpenStack?? All I see is "Status: 400, Reason: Bad Request"

P.S. I tried using ActionResponse to capture it, but looks like it returns Subnet.. Any help?

     {
            "subnet" : {
             "name" : "ssadasdsa",
              "cidr" : "1.0.0.0",
              "enable_dhcp" : false,
             "network_id" : "4337f21c-7016-49dd-b3bd-d212ce450e97",
            "tenant_id" : "f629477bddca4cbdb106844901b19b6c",
           "ip_version" : 4
       }
    }

Feb 20, 2015 12:10:24 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Client response received on thread http-bio-80-exec-8
2 < 400
2 < Connection: keep-alive
2 < Content-Length: 125
2 < Content-Type: application/json; charset=UTF-8
2 < Date: Fri, 20 Feb 2015 20:09:46 GMT
2 < X-Openstack-Request-Id: req-a8768a87-6350-4774-b6f8-e3baa887179d
{"NeutronError": "Invalid input for cidr. Reason: '1.0.0.0' isn't a recognized IP subnet cidr, '1.0.0.0/32' is recommended."}

ClientResponseException{message=Status: 400, Reason: Bad Request, status=400, status-code=BAD_REQUEST}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:53)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:17)
	at org.openstack4j.connectors.jersey2.HttpResponseImpl.getEntity(HttpResponseImpl.java:60)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:169)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:163)

**Comment by gondor** [comment]
So the underlying error against OpenStack seems valid since you didn't specify a valid CIDR.  However we should of been smarter in parsing out the underlying error message into the exception.

I just put a fix in to encapsulate the proper message in the currently thrown exception.  The exception message in your case above would have the test "Invalid input for cidr. Reason: '1.0.0.0' isn't a recognized IP subnet cidr, '1.0.0.0/32' is recommended" and still be coded as a 400 since OpenStack states the error code,

Checked in the fix and deployed a new 2.0.2-SNAPSHOT

**Comment by vishvesh** [comment]
Works.. Thanks..
