### ISSUE TITLE
Configuring connection pooling feature for underlying client connectors

### ISSUE THREAD

**Issue by symcssn** [gondor/openstack4j#267]
Hi,

Is there a way to configure connection management/pooling via the openstack4j client? For example, if we are using the apache http-client connector (which is internally using a PoolingHttpConnectionManager), is there a way to configure the maximum number of connections allowed at a time? The Config class would be a great class to add support for this. Currently, the Config class provides some properties that are used by these http clients.

Thanks!

**Comment by gondor** [comment]
@symcssn Currently we don't have these options but I like the idea.  You are correct that Config would be the best place to add these controls.  

To create the HttpClient we've been using HttpClientBuilder.  Do you know if what your looking for is a method off of that builder?  Let me know what you'll need and I can map it into the Config and HttpClientBuilder or underlying client that's built from it.

Jeremy

**Comment by symcssn** [comment]
For the openstack4j-httpclient connector, it is much simpler. You can either specify the parameters to HttpClientBuilder or add the values into System.properties for the property "http.maxConnections". 

It might be a bit more complicated with the openstack4j-jersey2 connector.. Currently, the jersey2 connector is backed directly by java net client. A thread pool needs to be implemented in between the two in order to have connection pools. The only configurations that can be specified are mentioned here: http://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html. While some of this is useful for configuring the client, it is not enough for pooling support.

Another way to utilize jersey with connection pool is to back it by an Apache client. This is a relevant example:  http://www.theotherian.com/2013/08/jersey-client-2.0-httpclient-timeouts-max-connections.html

To answer your question about methods of the HttpClientBuilder that can help with pooling, there are two methods that are useful: `setMaxConnTotal` & `setMaxConnPerRoute`.

**Comment by gondor** [comment]
Great and thanks for the extra details.   I'm actually thinking of adding connector specific options using generics with the Config object since as you pointed out some connectors won't support certain options.

Example:
```java
Config c = Config.newConfig().withConnectionTimeout(10)
                             .with(HttpClientOpts.maxConnTotal(5));
```
In the example above HttpClientOpts would only live if the httpclient connector is a dependency.  This way addon options would only be specific to the actual connector your using and the extra options live with that code.

What are your thoughts on this proposal?

**Comment by symcssn** [comment]
Sorry for the late reply. 

Would we need an HttpClientOpts? It seems a little bit redundant. The Config class is already being used to configure the http clients. You don't necessarily need a "set" method, but you can still keep things fluent. You can add method inside Config:

```java
public Config withMaxConnections(int);
```

This seems consistent with the way the Config class is currently designed.

The advantage of using the HttpClientOpts is if you want to package different versions of HttpClientOpts with different connector packages. 

The decision is yours since you have better insights about the current design and future designs. Both styles are okay depending on how you plan to integrate client configurations

**Comment by gondor** [comment]
Well, my biggest thoughts is not every connector supports a maxConnection option and the config is global (same Config) is used by all the connectors.  

I guess I could document that on the withMaxConnections(int) that it may not be supported by the chosen connector.

Does that make sense?

**Comment by symcssn** [comment]
Yes that makes sense.

**Comment by gondor** [comment]
Sorry, this issue slipped through he cracks and I forgot to complete it.  The change is in and a new 2.0.3-SNAPSHOT has been deployed.

Only HttpClient currently uses these options below:
```java
Config c = Config.newConfig().withMaxConnections(5).withMaxConnectionsPerRoute(2);
```

**Comment by symcssn** [comment]
Thanks! :)

**Comment by symcssn** [comment]
Aslo, I want to mention that the client builder should be shared by different instances of HttpCommand, otherwise each request will have its own pool

**Comment by gondor** [comment]
So the connectors options are pretty new and still in early stages.  I recently through them together starting in the 2.0.0 to give people options with the notion they were beta until the kinks got worked out.  Jersey has been our original connector since day one which is the most stable.

That being said the above ^^ feedback is appreciated since it will help stabilize the connector.  My question for you is if I ended up making the build a singleton like you mention does it handle different pools automatically for different host endpoints?   I'm thinking of scenarios where you may be managing various OpenStack deployments in a EE container.  Would a singleton still be acceptable in these situations.

Thanks,

Jeremy

**Comment by gondor** [comment]
Will address the singleton in the next release
