### ISSUE TITLE
Quota set volume,gigabytes is always 0 and instances do not be changed

### ISSUE THREAD

**Issue by benxiaohai1212** [gondor/openstack4j#282]
Im using a Openstack june infra and openstack4j to connect a java client. It seems that the storage quota value return in getGigabytes and getVolume() is always 0, getInstances() not be changed,

I examined the it resources quota, compute and volume request address is different.Through the compute is can not get the volume of the quota.

thank you!

**Comment by gondor** [comment]
I believe these items were dropped in the latest OpenStack release.  Here's the raw response I get from my JUNO install.
```
{"quota_set": {"injected_file_content_bytes": 10240, "metadata_items": 128, "server_group_members": 10, "server_groups": 10, "ram": 51200, "floating_ips": 10, "key_pairs": 100, "id": "80f4ab854e5343f09c2fee63031216e9", "instances": 10, "security_group_rules": 20, "injected_files": 5, "cores": 20, "fixed_ips": -1, "injected_file_path_bytes": 255, "security_groups": 10}}
```
As you can see there is no gigabytes or volumes anymore.  Try your deployment and see what's returned.  Since OpenStack4j has a java object around the expected results any properties that don't come back in the response will be java's initial value (int's initialize to 0) for example.

To see your raw response turn on http logging before your call:
```java
        OSFactory.enableHttpLoggingFilter(true);
```

Let me know what you find

**Comment by benxiaohai1212** [comment]
I know why updateForTenant modify the number of instances of unmodified success because NovaQuotaSetUpdate private Integer instances;Without annotation @ JsonProperty (" instances ")

**Comment by gondor** [comment]
Thanks, fix checked in and snapshot re-deployed

**Comment by gondor** [comment]
Deploying 2.0.2 Release Tonight - Closing - Re-Open or Comment if issue was not resolved
