### ISSUE TITLE
The KeystoneServiceEndpoint miss @JsonRootName("endpoint")

### ISSUE THREAD

**Issue by tangxiaodon89** [gondor/openstack4j#403]
In the Class org.openstack4j.openstack.identity.domain.KeystoneServiceEndpoint
Miss the annotation ‘@JsonRootName’, so the create method can't work.

@JsonIgnoreProperties(ignoreUnknown=true)
@JsonRootName("endpoint")
public class KeystoneServiceEndpoint implements ServiceEndpoint {

**Comment by gondor** [comment]
Sorry, I missed seeing this issue.  Can you provide an example of how you were using OpenStack4j when you got this error?  What version of OpenStack (deployed) are you testing against

**Comment by tangxiaodon89** [comment]
The kilo version of OpenStack.
I use the method org.openstack4j.openstack.identity.internal.ServiceManagerServiceImpl.createEndpoint
to create a endpoint for service.
Got an error that the request entity has not JsonRootName.

v2 version api support this request

This is the request info.
![image](https://cloud.githubusercontent.com/assets/11000963/8372819/544dd71a-1c19-11e5-8469-83fd74b20808.png)

**Comment by gondor** [comment]
Ok thanks for the update.  We have not tested against Kilo yet since it's fairly new and the majority of the community is still on Juno or Icehouse.   I'll need to run some backwards compatibility tests to make sure this doesn't affect previous versions.   If you find anything else while testing against Kilo please feel free add separate issues.  Ideally the topic of the issue should involve "some problem on Kilo" so we can group these issues.

**Comment by gondor** [comment]
Issue resolved and a new 2.0.4 SNAPSHOT deployed
