### ISSUE TITLE
Update jackson to 2.7 for v3

### ISSUE THREAD

**Issue by gschukin** [gondor/openstack4j#563]
Update jackson from 2.4 to 2.7

**Comment by sachinwalia2k8** [comment]
@gondor @gschukin - if jackson is upgraded to 2.7 then JDK 6 may be used as a dependency. However 2.8 onwards all support for JDK 6 will be dropped. Is there a timeline until when you want to support JDK 6?

**Comment by gondor** [comment]
@sachinwalia2k8 , @auhlig @dhague have been working on the new seamless V3 integration in a v3_collaboration branch.  This will end up being merged in and bump OpenStack4j from the 2.x to 3.0.0 release.   At that time the ongoing work will be in OpenStack4j version 3 (new master) which has also dropped JDK 1.6.

@auhlig When do you anticipate the release of your V3 work and OpenStack4j version 3?

**Comment by auhlig** [comment]
@gondor Creating, handling and merging in so many small PRs for the identity v3 work was good in terms of reviewing the code but took way longer than actually writing all of it. 
Anyway, I think you can start the countdown as we're about 4 PRs away from the release.

**Comment by gondor** [comment]
@auhlig Thats exciting news!  You guys have done a fantastic job. Be proud when we release version 3 :)

@sachinwalia2k8 Come to think of it I don't think bumping up Jersey will hurt anything.  I forgot I created two separate connectors.  The default connector which is why this would address and then a special jersey-jdk16 openstack4j connector that can be used instead which is running on an older version.  Maybe I'm missing something else from this request.

**Comment by gschukin** [comment]
I think that the JDK baseline for Jackson 2.7 is JDK 1.7.

**Comment by sachinwalia2k8** [comment]
@gschukin - JDK 6 is supported until Jackson 2.7. Beginning 2.8 it'll be JDK 7 and onwards only.
