### ISSUE TITLE
httpclient connector doesn't support PATCH calls

### ISSUE THREAD

**Issue by batdesso** [gondor/openstack4j#600]
The current implementation of org.openstack4j.core.transport.HttpMethod specifies all http methods:

**HEAD, GET, POST, PUT, PATCH, DELETE, OPTIONS, TRACE**

but in org.openstack4j.connectors.httpclient.HttpCommand.initialize()  /apache httpclient connector/ 
the following methods - **PATCH, OPTIONS and TRACE**  are not supported and by default the implementation replaces such calls with **GET**.

**Comment by auhlig** [comment]
Hi @batdesso, 
In case of the http PATCH method, which is required for some update()-calls in the identity v3 part, we were able to fix this by adding a workaround.
If you look at e.g. https://github.com/gondor/openstack4j/blob/v3_collaboration/connectors/jersey2/src/main/java/org/openstack4j/connectors/jersey2/HttpCommand.java#L52-L54 you could add the OPTIONS, TACE method.
A

**Comment by dbantchovski** [comment]
Hi @auhlig 

Looking at org.openstack4j.openstack.internal.BaseOpenStackService.java  I found that the following methods are used: - **GET, POST, PUT, DELETE, HEAD and PATCH**.
On the other hand, the httpclient connector doesn’t provide a way to execute a PATCH call, which seems inconsistent. The problem is related to the httpclient connector only, because the other http connectors builds their requests in a generic way, for example / org.openstack4j.connectors.jersey2.HttpCommand.java/:

response = invocation.method(request.getMethod().name(), getEntity());

while the httpclient uses a switch on requested http method type and executes a different code. Unfortunately a case for **PATCH** is missing, which causes execution of **GET **instead of **PATCH**.

By the way, I proposed a fix.

PS: **OPTIONS** and **TRACE **methods are never used.
